services:
  # Backend Service
  - type: web
    name: shanture-analytics-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: shanture-analytics-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://shanture-analytics-frontend.onrender.com
      - key: PORT
        value: 10000

  # Frontend Service
  - type: web
    name: shanture-analytics-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://shanture-analytics-backend.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://shanture-analytics-backend.onrender.com

databases:
  - name: shanture-analytics-db
    databaseName: shanture-analytics
    user: shanture-user

